In [25]:
import pandas as pd

In [26]:
data1 = pd.read_excel('/kaggle/input/kdsh-data-solution-task-2/HCP_Data_KDAG_Hackathon/HCP_Data_KDAG_Hackathon.xlsx')

In [27]:
data1.head()

Physician_ID  Time_Period  Brand_Rx  Market_Rx  Sales_Rep_Calls  \
0     axt00001     20190104       0.0    2.80567                1   
1     axt00001     20190111       0.0   20.57312                1   
2     axt00001     20190118       0.0    6.16010                1   
3     axt00001     20190125       0.0    8.95501                1   
4     axt00001     20190201       0.0    9.13793                1   

   Samples_Dropped Physician_Segment  Emails_Delivered  \
0                0             3-Low                 0   
1                0             3-Low                 0   
2                0             3-Low                 0   
3                5             3-Low                 0   
4                0             3-Low                 0   

   Speaker_Programs_Attended  Vouchers_Dropped      Specialty  
0                          0                 0  Dermatologist  
1                          0                 0  Dermatologist  
2                          0                 0  Dermatologist  
3                          0                 0  Dermatologist  
4                          0                 0  Dermatologist

In [28]:
data = {
    "Time Period":data1['Time_Period'],
    "Brand_Rx":data1['Brand_Rx']
}

In [29]:
df= pd.DataFrame(data)

In [30]:
x = df.iloc[1:57]

In [31]:
months= []
years=[]
day=[]
import numpy as np
sliced_text = slice(6)
for i in x['Time Period']:
    years.append((int)(str(i)[0:4]));
    months.append((int)(str(i)[4:6]));
    day.append((int)(str(i)[6:8]));

# convert into one matrix
X = np.array([day, months, years]).T

In [32]:
def findBrandRx(a,b):
    x1 = df.iloc[a:b]
    from sklearn.ensemble import RandomForestRegressor

    # fit the model
    my_rf = RandomForestRegressor()
    my_rf.fit(X, x1['Brand_Rx'])

    # predict for the feb 1st week
    day1 = [7]
    month1 = [2]
    year1 = [2020]

    X1 = np.array([day1,month1,year1]).T

    preds = my_rf.predict(X1)
    
    return preds;

In [33]:
a=1
b=57
Estimated_Rx = []
for i in range(10000):
    brand_Rx=findBrandRx(a,b)
    Estimated_Rx.append(brand_Rx)
    print(a," ",b," ",brand_Rx)
    a += 57
    b += 57

1   57   [1.09325]
58   114   [0.]
115   171   [0.14642]
172   228   [0.63315]
229   285   [0.18638]
286   342   [2.13852]
343   399   [0.81615]
400   456   [0.7053]
457   513   [0.]
514   570   [2.50451]
571   627   [0.]
628   684   [0.10816]
685   741   [5.65292]
742   798   [3.32769]
799   855   [0.37517]
856   912   [0.56229]
913   969   [1.55011]
970   1026   [0.]
1027   1083   [0.73485]
1084   1140   [1.62947]
1141   1197   [0.85062]
1198   1254   [0.07675]
1255   1311   [1.14326]
1312   1368   [1.04205]
1369   1425   [0.3203]
1426   1482   [0.74304]
1483   1539   [0.]
1540   1596   [0.58053]
1597   1653   [0.25025]
1654   1710   [3.05203]
1711   1767   [1.2297]
1768   1824   [0.46348]
1825   1881   [0.45526]
1882   1938   [0.03155]
1939   1995   [0.]
1996   2052   [0.75]
2053   2109   [0.32383]
2110   2166   [0.33835]
2167   2223   [0.]
2224   2280   [0.49839]
2281   2337   [0.98484]
2338   2394   [0.]
2395   2451   [0.]
2452   2508   [1.45956]
2509   2565   [0.73112]
2566   262

In [34]:
Estimated_Rx

[array([1.09325]),
 array([0.]),
 array([0.14642]),
 array([0.63315]),
 array([0.18638]),
 array([2.13852]),
 array([0.81615]),
 array([0.7053]),
 array([0.]),
 array([2.50451]),
 array([0.]),
 array([0.10816]),
 array([5.65292]),
 array([3.32769]),
 array([0.37517]),
 array([0.56229]),
 array([1.55011]),
 array([0.]),
 array([0.73485]),
 array([1.62947]),
 array([0.85062]),
 array([0.07675]),
 array([1.14326]),
 array([1.04205]),
 array([0.3203]),
 array([0.74304]),
 array([0.]),
 array([0.58053]),
 array([0.25025]),
 array([3.05203]),
 array([1.2297]),
 array([0.46348]),
 array([0.45526]),
 array([0.03155]),
 array([0.]),
 array([0.75]),
 array([0.32383]),
 array([0.33835]),
 array([0.]),
 array([0.49839]),
 array([0.98484]),
 array([0.]),
 array([0.]),
 array([1.45956]),
 array([0.73112]),
 array([1.1161]),
 array([0.]),
 array([1.64717]),
 array([0.40685]),
 array([0.00879]),
 array([0.16302]),
 array([2.94234]),
 array([0.]),
 array([2.66644]),
 array([0.]),
 array([0.67702]),
 ar

In [35]:
Expected_Trx = []
for i in Estimated_Rx:
    Expected_Trx.append(i[0])

In [36]:
Expected_Trx

[1.0932499999999994,
 0.0,
 0.14642000000000002,
 0.6331500000000005,
 0.18638000000000002,
 2.138520000000001,
 0.8161500000000004,
 0.7052999999999998,
 0.0,
 2.5045099999999993,
 0.0,
 0.10815999999999999,
 5.652919999999999,
 3.3276900000000014,
 0.3751699999999999,
 0.5622900000000001,
 1.5501100000000003,
 0.0,
 0.7348499999999996,
 1.6294700000000018,
 0.8506199999999998,
 0.07675,
 1.14326,
 1.0420500000000004,
 0.3202999999999999,
 0.7430399999999996,
 0.0,
 0.5805300000000001,
 0.2502500000000001,
 3.0520299999999985,
 1.2297000000000005,
 0.4634800000000002,
 0.45526000000000005,
 0.031549999999999995,
 0.0,
 0.7499999999999997,
 0.32382999999999995,
 0.33834999999999993,
 0.0,
 0.4983900000000005,
 0.9848399999999993,
 0.0,
 0.0,
 1.4595600000000004,
 0.7311199999999995,
 1.1161000000000003,
 0.0,
 1.6471699999999994,
 0.40685000000000004,
 0.00879,
 0.16301999999999997,
 2.9423399999999997,
 0.0,
 2.666440000000002,
 0.0,
 0.6770200000000007,
 0.0,
 0.3856600000000001,
 3.

In [37]:
data5 = pd.read_csv('/kaggle/input/kdsh-data-solution-task-2/sample_submission.csv')

In [38]:
data5

Physician_ID  Expected_TRx
0        axt00001           0.0
1        axt00002           0.0
2        axt00003           0.0
3        axt00004           0.0
4        axt00005           0.0
...           ...           ...
9995     axt09996           0.0
9996     axt09997           0.0
9997     axt09998           0.0
9998     axt09999           0.0
9999     axt10000           0.0

[10000 rows x 2 columns]

In [46]:
data5['Expected_TRx']=Expected_Trx

In [47]:
data5

Physician_ID  Expected_TRx
0        axt00001       1.09325
1        axt00002       0.00000
2        axt00003       0.14642
3        axt00004       0.63315
4        axt00005       0.18638
...           ...           ...
9995     axt09996       0.00000
9996     axt09997       0.40560
9997     axt09998       0.00000
9998     axt09999       1.46076
9999     axt10000       0.09233

[10000 rows x 2 columns]

In [48]:
filename = 'solution_task2.csv'
data5.to_csv(filename,index=False)

In [42]:

# plot what has been learned
# plt.plot(x.index, x['Brand_Rx'])
# plt.plot(x.index, preds)

In [43]:
# len(preds)

In [44]:
# 01-02-2019

# preds